version: "3.8"

services:

  frontend:
    container_name: frontend
    image: frontend:latest
    restart: unless-stopped
    env_file:
      - .env
    build: ./front
    ports:
      - ${FRONT_CLIENT_PORT}:${FRONT_CLIENT_PORT}
    environment:
      - STYLE=css
    volumes:
      - ./front/src/:/angular-app
      - /app/node_modules
    command: ng serve

  backend:
    container_name: backend
    image: backend:latest
    env_file:
      - .env
    depends_on:
      - postgresdb
    build: ./backend
    command: "npm run start:dev"
    ports:
      - ${BACK_CLIENT_PORT}:${BACK_CLIENT_PORT}
    volumes:
      -  ./backend:/app/src 
    stdin_open: true
    tty: true

  postgresdb:
    container_name: postgres_drive
    image: postgres:latest
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./database/:/docker-entrypoint-initdb.d/
      - db:/var/lib/postgresql/data
    ports:
      - ${DOCKER_DB_PORT}:${CLIENT_DB_PORT}
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}

  adminer:
    image: dpage/pgadmin4
    container_name: pgadmin
    env_file:
      - .env
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - ${DOCKER_ADMINER_PORT}:${CLIENT_ADMIN_PORT}
    depends_on:
      - postgresdb
   
volumes:
  db:
    

