version: "3.8"

services:

  frontend:
    container_name: frontend
    image: frontend:latest
    restart: unless-stopped
    build: ./front
    ports:
      - "4200:4200"
    environment:
      - STYLE=css
    volumes:
      - ./front/src/:/angular-app
      - /app/node_modules
    command: ng serve

  backend:
    container_name: backend
    image: backend:latest
    depends_on:
      - postgresdb
    build: ./backend
    command: "npm run start:dev"
    ports:
      - "3000:3000"
    volumes:
      -  ./backend:/app/src 
    stdin_open: true
    tty: true

  postgresdb:
    container_name: postgres_drive
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - ./database/:/docker-entrypoint-initdb.d/
      - db:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=my_database
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword

  adminer:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@example.com
      - PGADMIN_DEFAULT_PASSWORD=adminpassword
    ports:
      - "8081:80"
    depends_on:
      - postgresdb
   
volumes:
  db:
    

